server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka-8701:8701/eureka/
    registry-fetch-interval-seconds: 30
    enabled: true
spring:
  application:
    name: api-passenger